=== quguoxin/all_study/框架/struts2_qgx_demo/src/main/resources/tlc_struts.dtd
<!ELEMENT tlc_struts (actions)>
<!ELEMENT actions (action*)>
<!ELEMENT action (result*)>
<!ELEMENT result (#PCDATA)>
<!ATTLIST action name CDATA #REQUIRED class CDATA #REQUIRED>
<!ATTLIST result name CDATA #REQUIRED redirect (true|false) "false">

=== quguoxin/all_study/框架/struts2_qgx_demo/src/main/resources/tlc_struts.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE tlc_struts SYSTEM "D:\struts2_qgx_demo\src\main\resources\tlc_struts.dtd">
<tlc_struts>
    <actions>
        <action name="login" class="com.qgx.www.action.LoginAction">
            <result name="success">login_success.jsp</result>
            <result name="fail">error.jsp</result>
        </action>
        <action name="reg" class="com.qgx.www.action.RegAction">
            <result name="success">reg_success.jsp</result>
            <result name="fail">error.jsp</result>
        </action>
    </actions>
</tlc_struts>
